'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { ThirdwebWeb3Provider } from '@3rdweb/hooks';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
// title: 'Create Next App',
// description: 'Generated by create next app',
// }

const supportedChainIds = [11155111]
const connectors = { injected: {}, }

export default function RootLayout({ children }) {
// wrapping the whole app in the thirdweb for authentication
// this will also let us access the authentication related code to be accessible from any directory of the project
  return (
          <ThirdwebWeb3Provider supportedChainIds={supportedChainIds} connectors={connectors}>    
          <html lang="en">
          <body className={inter.className}>{children}</body>
          </html>
          </ThirdwebWeb3Provider>
      )
  }

